### ISSUE TITLE
Package pwa file generates which generate pub warning

### ISSUE THREAD

**Issue by daftspaniel** [isoos/pwa#13] opened 2017-07-16 04:49 UTC
> Suggestions:
> * The name of "lib/pwa/offline_urls.g.dart", "offline_urls.g", may only contain letters, numbers, and underscores.
>   Using a valid Dart identifier makes the name usable in Dart code.
> 
Can the file be renamed?

**Comment by isoos** [comment] 2017-07-16 07:36
Duplicate of https://github.com/isoos/pwa/issues/12

**Closed as completed by isoos** 2017-07-16 07:36 UTC
