### ISSUE TITLE
Feature to set exculsions for offline urls

### ISSUE THREAD

**Issue by daftspaniel** [isoos/pwa#9] opened 2017-06-02 05:20 UTC
Running PWA on an AngularDart application creates a very large list (hundreds) in offline_urls.g.dart. e.g.
```
  './packages/intl/src/data/dates/patterns/af.json',
  './packages/intl/src/data/dates/patterns/am.json',
 ...

  './packages/np8080/toolbar/menu/menu_template.html',
  './packages/np8080/toolbar/toolbar_component.html',
...
```
It would be useful to exclude paths not needed for the final build i.e./packages

The exception to this would be packages/browser/dart.js and interop.js which I believe are required.

Thanks!

**Comment by isoos** [comment] 2017-06-05 22:05
The `bin/pwa.dart` has an `exclude` flag that should be able to exclude such file paths. E.g. try `--exclude packages/np8080/**.html` to exclude the mentioned `.html` files.

It is safe to exclude leftover build artifacts, but you should keep everything that is loaded asynchronously. I'm not entirely sure whether the `intl` would need those files, I have only vague memories about that package.

**Comment by erikist** [comment] 2017-06-14 19:27
@isoos can you exclude external scripts from caching?

**Comment by isoos** [comment] 2017-06-14 19:29
@erikist: could you give me an example of what you would like to exclude?

**Comment by daftspaniel** [comment] 2017-06-14 19:33
This worked for me - pub run pwa --exclude packages/** though I'd rather have it in code/config,

**Comment by erikist** [comment] 2017-06-14 19:38
Bear with me a bit on this, as I am new to angular and PWAs in general: I have an angular2 app that uses the `google_maps` package which requires the following in the head section:
```
    <script src="https://maps.googleapis.com/maps/api/js?key=my_api_key"></script>
```

After setting up `pwa` I can now use the site in offline mode, however, regardless of whether I am online or offline, my map now fails to load. I am unsure exactly why. Offline, it makes sense, I need the internet to use google maps. But when online, I would have expected the map to load. 

Additionally, I am getting a new error after using the `pwa` package: 

```
EXCEPTION: NoSuchMethodError: method not found: '$index' (J.getInterceptor$asx(...).$index is not a function)
STACKTRACE: 
TypeError: J.getInterceptor$asx(...).$index is not a function
    at Object.J.$index$asx (http://localhost:56480/main.dart.js:73868:43)
    at Object.LatLng$ (http://localhost:56480/main.dart.js:68566:66)
    at http://localhost:56480/main.dart.js:65623:24
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:56480/main.dart.js:7234:15)
    at _wrapJsFunctionForAsync_closure.dart._wrapJsFunctionForAsync_closure.call$2 (http://localhost:56480/main.dart.js:7739:14)
    at _awaitOnObject_closure.dart._awaitOnObject_closure.call$1 (http://localhost:56480/main.dart.js:7727:34)
    at StaticClosure.dart._rootRunUnary.func (http://localhost:56480/main.dart.js:7583:18)
    at _ZoneDelegate.runUnary$3 (http://localhost:56480/main.dart.js:10705:41)
    at NgZone.dart.NgZone._runUnary$5 (http://localhost:56480/main.dart.js:31234:24)
    at Object.eval (eval at Closure_forwardCallTo (http://localhost:56480/main.dart.js:4829:14), <anonymous>:2:47)
ORIGINAL EXCEPTION: NoSuchMethodError: method not found: '$index' (J.getInterceptor$asx(...).$index is not a function)
```

This seems to be related to the google maps v3 scripts being loaded from cache, but again, pardon my ignorance.

I am guessing this has to do with caching, but where the problem is coming from is beyond me! Let me know if you would like any additional information.

**Comment by erikist** [comment] 2017-06-14 20:18
@isoos I have created a sample application I can share with you, though I request either that I DM you a google maps key via gitter or email or something, or you just generate your own. [The library](https://github.com/erikist/pwa_google_maps) was verified to work before following the exact steps available for [pwa_defaults](https://github.com/isoos/pwa/tree/master/examples/pwa_defaults)

I used a slightly modified version of this [tutorial](https://medium.com/dartlang/google-maps-with-angulardart-a75f7f84f941) to generate the working maps project, if you are interested. 

In order to use the attached library, clone it down and alter the `index.html` `script` tag with the google maps API with a valid key. If you would like me to send you a key, you can shoot me an email `erik.rahtjen@stablekernel.com`

**Comment by isoos** [comment] 2017-06-15 08:44
Closing this, as the title is a about very different issue which got resolved, and now the topics get mixed. Feel free to reopen a ticket to discuss what should be automatically excluded from offline urls.

Follow-up on the exception with maps: https://github.com/isoos/pwa/issues/10

**Closed as completed by isoos** 2017-06-15 08:44 UTC
